"""
Signal event dataclass.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass
class SignalEvent:
    """Represents a trading signal generated by a strategy."""

    symbol: str
    signal: str  # 'long', 'short', 'close', 'hold'
    strategy_name: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: dict[str, Any] = field(default_factory=dict)
